version: '3'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    env_file:
      - .env
    ports:
      - ${NGINX_PORT}:443
    networks:
      - network

networks:
  network:
    driver: bridge