version: '3'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx #build a custom Docker image for the service
    restart: always
    ports:
      - ${NGINX_PORT}:443
    networks:
      - inception
    depends_on:
      - wordpress
    volumes:
      - wp_website:/var/www/html

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    ports:
      - ${WORDPRESS_PORT}:9000
    networks:
      - inception
    restart: always
    depends_on:
      - mariadb
    volumes:
      - wp_website:/var/www/html

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    ports:
      - ${DB_PORT}:3306
    networks:
      - inception
    restart: always
    volumes:
      - wp_data:/var/lib/mysql
      # create a Docker volume wp_data and 
      # mount it at the /var/lib/mysql

  static:
    container_name: static
    build: ./requirements/bonus/static
    restart: always
    ports:
      - 1234:1234
    networks:
      - inception

  cadvisor:
    container_name: cadvisor
    build: ./requirements/bonus/cadvisor
    restart: always
    ports:
      - 6593:8080
    networks:
      - inception
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

# Volume definition
volumes:
  wp_website:
    driver: local
    driver_opts:
      type: none
      device: /home/plau/data/wp_website
      o: bind
      # specifies mount options for the volume
      # volume is mounted as a bind mount,
      # where the source directory on the host is directly mounted into the container
  wp_data:
    driver: local
    driver_opts:
      type: none
      device: /home/plau/data/wp_data
      o: bind

# Docker-network that establishes the connection between containers
networks:
  inception:
    driver: bridge
